development:
  adapter: postgresql
  encoding: unicode
  database: interview
  pool: 5
  username: postgres
  password: olamilekan
  timeout: 5000

test:
  adapter: postgresql
  encoding: unicode
  database: interview_test
  pool: 5
  username: postgres
  password: olamilekan
  timeout: 5000